name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.9.5
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "pnpm"
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - run: |
          pnpm i
          pnpm fmt --check
          pnpm lint
          pnpm build:prod

      - if: startsWith(github.ref, 'refs/tags/v') && github.repository == 'zhmushan/scrollcat'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
